# Generated by Django 5.2.6 on 2025-09-10 12:11

import django.core.validators
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='MovieID')),
                ('title', models.CharField(max_length=200, verbose_name='MovieTitle')),
                ('actor1', models.CharField(max_length=100, verbose_name='Actor1Name')),
                ('actor2', models.CharField(blank=True, max_length=100, verbose_name='Actor2Name')),
                ('director', models.CharField(max_length=100, verbose_name='DirectorName')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Other', 'Other')], max_length=20, verbose_name='MovieGenre')),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(videos.models.current_year)], verbose_name='ReleaseYear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
